Add support for na = n/a becoming N/A
reZach/grammarify pull request #2
Opened 2019-11-12 13:49 UTC by ajoslin103

This is a special case, perhaps not for everyone

2019-11-12 18:16 UTC, reZach requested changes

2019-11-12 18:16 UTC, reZach commented on index.js
> +        "na": "n/a",
@ajoslin103 I'd prefer if we put both mappings in the list, rather than use `.toUpperCase()`. I feel the use of `.toUpperCase()` isn't needed and we can map the words directly like so:

```
"na": "N/A",
"n/a": "N/A"
```

If there is push back that "na" doesn't map to "nah", we can decide then how to proceed.

Thanks for making a PR to this repo!

2019-11-12 19:34 UTC, ajoslin103 commented
Excellent change to the modification -- always better to avoid adding special-case code

I didn't notice that you were traversing the mappings until there were no more replacements.

Thank you for making this Repo -- I found it years later, at a time most opportune !!

2019-11-13 04:16 UTC, merged

2019-11-13 05:00 UTC, reZach commented
@ajoslin103 The fix has been pushed to **v1.0.2** (it is live on NPM now).

2019-11-13 14:16 UTC, ajoslin103 commented
I'm sorry, but the index.min.js doesn't include the change - do I have to do something else?

2019-11-13 15:06 UTC, reZach commented
@ajoslin103 oops! I can do that tonight, in the meantime can you use **index.js** until then? Sorry!

2019-11-14 05:11 UTC, reZach commented
@ajoslin103 **index.min.js** has now been updated with the changes.

2019-11-14 12:10 UTC, ajoslin103 commented
thanks!

> On Nov 14, 2019, at 12:11 AM, reZach <notifications@github.com> wrote:
> 
> @ajoslin103 <https://github.com/ajoslin103> index.min.js has now been updated with the changes.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub <https://github.com/reZach/grammarify/pull/2?email_source=notifications&email_token=AADML5I7ZNDRUO3DSVLD5DDQTTMZFA5CNFSM4JMDX3D2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEEATMOY#issuecomment-553727547>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/AADML5LK6RCBC4NHF626B2DQTTMZFANCNFSM4JMDX3DQ>.
>